### ISSUE TITLE
Setup backend to serve the  react frontend

### ISSUE THREAD

**Issue by AviatorIfeanyi** [zurichat/zc_plugin_company_shift#110]
The node.js back-end should serve the react front-end files after the front-end files have been bundled for production

https://employeeshift.zuri.chat
https://employeeshift.zuri.chat/api

PR
https://github.com/zurichat/zc_plugin_company_shift/pull/112

@Aviator

**Comment by depecode** [comment]
LTGM

**Comment by nwazuo** [comment]
Hello guys, is there any issue with this? I noticed it was closed and then reopened.

**Comment by johnokwajebi** [comment]
> Hello guys, is there any issue with this? I noticed it was closed and then reopened.

issues have to be opened for review

**Comment by markessien** [comment]
-nice work
